language: c
compiler:
  - clang
  - gcc
env:
  - VER=3.0
before_install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https python-docutils
  - curl -s https://repo.varnish-cache.org/ubuntu/GPG-key.txt |
    sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-$VER" |
    sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update
  - sudo apt-get install varnish libvarnishapi-dev
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" && make check
